# Generated by Django 5.0.6 on 2024-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemonsearch', '0002_delete_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('percentage_male', models.FloatField(blank=True, null=True)),
                ('type1', models.TextField()),
                ('type2', models.TextField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('capture_rate', models.FloatField(blank=True, null=True)),
                ('generation', models.IntegerField(blank=True, null=True)),
                ('is_legendary', models.BooleanField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemon',
                'managed': False,
            },
        ),
    ]
